package main

import (
	"fmt"
	"math/rand"
	"time"
)

func main() {
	jokes := []string{
		"Why don't scientists trust atoms? Because they make up everything!",
		"Why don't eggs tell jokes? They'd crack each other up!",
		"Why did the tomato turn red? Because it saw the salad dressing!",
		"What do you call a fake noodle? An impasta!",
		"Why did the scarecrow win an award? Because he was outstanding in his field!",
		"Why don't lobsters share? Because they're shellfish!",
		"What do you call a can opener that doesn't work? A can't opener!",
		"I told my wife she was drawing her eyebrows too high. She looked surprised!",
		"Why don't some couples go to the gym? Because some relationships don't work out!",
		"What do you call a bear with no socks on? Barefoot!",
		"Why did the bicycle fall over? Because it was two-tired!",
		"I'm reading a book about anti-gravity. It's impossible to put down!",
		"Why did the banana go to the doctor? He wasn't peeling well!",
		"Why did the astronaut break up with his girlfriend? Because he needed space!",
		"What do you call a group of cows playing instruments? A moo-sical band!",
		"Why did the baker go to the bank? He needed dough!",
		"Why did the mushroom go to the party? Because he was a fun-gi!",
		"Why did the computer go to the doctor? It had a virus!",
		"Why did the kid bring a ladder to school? He wanted to reach his full potential!",
		"What do you call a fish with no eyes? A fsh!",
		"Why did the orange stop in the middle of the road? Because it ran out of juice!",
		"Why did the rabbit go to the doctor? He had hare-loss!",
		"What do you call a dog that does magic tricks? A labracadabrador!",
		"Why did the kid become a baker? Because he kneaded the dough!",
		"Why did the turkey join the band? He was a drumstick!",
		"What do you call a cat that's a good listener? A purr-fect listener!",
		"Why did the elephant quit the circus? Because he was tired of working for peanuts!",
		"Why did the kid bring a magnet to school? He wanted to attract attention!",
		"What do you call a cow that plays hide-and-seek? A moo-ving target!",
		"Why did the chicken go to the doctor? He had fowl breath!",
		"Why did the kid become a master baker? Because he was egg-cellent!",
		"What do you call a dog that's a great dancer? A paw-fect dancer!",
		"Why did the banana split? Because it wasn't peeling well!",
		"Why did the kid bring a compass to school? He wanted to navigate his way to success!",
		"What do you call a cat that's a great singer? A mew-sical star!",
		"Why did the elephant go to the beauty parlor? Because he wanted a tusk-do!",
		"Why did the kid become a scientist? Because he was curious about the world!",
		"What do you call a dog that's a great artist? A paw-casso!",
		"Why did the rabbit go to the beauty parlor? Because he wanted a hare-do!",
		"Why did the kid bring a flashlight to school? He wanted to brighten up his day!",
		"What do you call a cat that's a great athlete? A purr-fect athlete!",
		"Why did the elephant quit his job? Because he was tired of working for peanuts!",
		"Why did the kid become a musician? Because he was a natural note-taker!",
		"What do you call a dog that's a great writer? A paw-etic writer!",
		"Why did the banana go to the doctor? He wasn't peeling well!",
		"Why did the kid bring a book to school? He wanted to get a head start on his education!",
		"What do you call a cat that's a great teacher? A purr-fect educator!",
		"Why did the elephant go to the gym? Because he wanted to get some tusk-cular strength!",
		"Why did the kid become a chef? Because he was a recipe for success!",
		"What do you call a dog that's a great inventor? A paw-ented inventor!",
		"Why did the rabbit go to the doctor? He had hare-loss!",
		"Why did the kid bring a pencil to school? He wanted to draw attention!",
		"What do you call a cat that's a great detective? A purr-fect detective!",
		"Why did the elephant go to the beauty parlor? Because he wanted a tusk-do!",
		"Why did the kid become a doctor? Because he wanted to help people feel better!",
		"What do you call a dog that's a great engineer? A paw-fect engineer!",
		"Why did the rabbit go to the gym? Because he wanted to get some hare-brained strength!",
		"Why did the kid bring a calculator to school? He wanted to get a head count!",
		"What do you call a cat that's a great mathematician? A purr-fect mathematician!",
		"Why did the elephant go to the amusement park? Because he wanted to have a tusk-tastic time!",
		"Why did the kid become a lawyer? Because he wanted to sue-per-ceed!",
		"What do you call a dog that's a great lawyer? A paw-some lawyer!",
		"Why did the rabbit go to the beauty parlor? Because he wanted a hare-do!",
		"Why did the kid bring a map to school? He wanted to navigate his way to success!",
		"What do you call a cat that's a great navigator? A purr-fect navigator!",
		"Why did the elephant go to the art museum? Because he wanted to see some tusk-masterpieces!",
		"Why did the kid become a artist? Because he was a brush with greatness!",
		"What do you call a dog that's a great artist? A paw-casso!",
		"Why did the rabbit go to the music store? Because he wanted to buy some hare-monies!",
		"Why did the kid bring a guitar to school? He wanted to strike a chord!",
		"What do you call a cat that's a great musician? A mew-sical star!",
		"Why did the elephant go to the dance studio? Because he wanted to learn some tusk-tastic moves!",
		"Why did the kid become a dancer? Because he was a step ahead!",
		"What do you call a dog that's a great dancer? A paw-fect dancer!",
		"Why did the rabbit go to the comedy club? Because he wanted to hare-larious!",
		"Why did the kid bring a joke book to school? He wanted to have a laugh-ing good time!",
		"What do you call a cat that's a great comedian? A purr-fect comedian!",
		"Why did the elephant go to the fashion show? Because he wanted to see some tusk-tastic designs!",
		"Why did the kid become a fashion designer? Because he was a cut above the rest!",
		"What do you call a dog that's a great fashion designer? A paw-some designer!",
		"Why did the rabbit go to the science fair? Because he wanted to show off his hare-brained ideas!",
		"Why did the kid bring a microscope to school? He wanted to get a closer look!",
		"What do you call a cat that's a great scientist? A purr-fect scientist!",
	}

	rand.Seed(time.Now().UnixNano())
	fmt.Println(jokes[rand.Intn(len(jokes))])
}
